//! Builds a byte-offset index into `vendor/carapace-specs.json` so the Tier
//! A `known_specs` module can deserialize exactly one tool's JSON object at
//! runtime instead of the whole 740-tool, 11 MB catalog (spec §7 Tier A,
//! "Storage").
//!
//! This runs once at compile time. It performs a structural scan of the raw
//! JSON bytes (not a full `serde_json::Value` parse, so byte offsets into
//! the *original* file are preserved) and emits a sorted
//! `[(tool_name, start, len)]` table plus the `_meta` fields as Rust source
//! into `OUT_DIR`, which `src/known_specs/mod.rs` includes with `include!`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let catalog_path = PathBuf::from(&manifest_dir).join("../vendor/carapace-specs.json");
    println!("cargo:rerun-if-changed={}", catalog_path.display());

    let bytes = fs::read(&catalog_path).unwrap_or_else(|e| {
        panic!(
            "failed to read vendored catalog at {}: {e}. This file must not be regenerated or deleted; see vendor/carapace-specs.json and scripts/vendor_carapace_specs.py.",
            catalog_path.display()
        )
    });

    let entries = scan_top_level_object(&bytes).unwrap_or_else(|e| {
        panic!(
            "failed to structurally scan {}: {e}",
            catalog_path.display()
        )
    });

    let mut meta_provider = String::new();
    let mut meta_source = String::new();
    let mut meta_source_dir = String::new();
    let mut meta_commit = String::new();
    let mut meta_generated = String::new();

    let mut tool_entries: Vec<(String, usize, usize)> = Vec::new();

    for (key, start, end) in entries {
        if key == "_meta" {
            let slice = std::str::from_utf8(&bytes[start..end]).expect("catalog is UTF-8");
            let meta: serde_json::Value = serde_json::from_str(slice).expect("_meta is valid JSON");
            meta_provider = meta["provider"].as_str().unwrap_or_default().to_string();
            meta_source = meta["source"].as_str().unwrap_or_default().to_string();
            meta_source_dir = meta["source_dir"].as_str().unwrap_or_default().to_string();
            meta_commit = meta["commit"].as_str().unwrap_or_default().to_string();
            meta_generated = meta["generated"].as_str().unwrap_or_default().to_string();
            continue;
        }
        tool_entries.push((key, start, end - start));
    }

    tool_entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str(
        "// @generated by mandible-extract/build.rs from vendor/carapace-specs.json. Do not edit.\n",
    );
    out.push_str(&format!(
        "pub(crate) const META_PROVIDER: &str = {meta_provider:?};\n"
    ));
    out.push_str(&format!(
        "pub(crate) const META_SOURCE: &str = {meta_source:?};\n"
    ));
    out.push_str(&format!(
        "pub(crate) const META_SOURCE_DIR: &str = {meta_source_dir:?};\n"
    ));
    out.push_str(&format!(
        "pub(crate) const META_COMMIT: &str = {meta_commit:?};\n"
    ));
    out.push_str(&format!(
        "pub(crate) const META_GENERATED: &str = {meta_generated:?};\n"
    ));
    out.push_str(&format!(
        "pub(crate) const TOOL_COUNT: usize = {};\n",
        tool_entries.len()
    ));
    out.push_str("pub(crate) static SPEC_INDEX: &[(&str, u32, u32)] = &[\n");
    for (name, start, len) in &tool_entries {
        out.push_str(&format!("    ({name:?}, {start}u32, {len}u32),\n"));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = PathBuf::from(out_dir).join("spec_index.rs");
    fs::write(&dest, out).expect("failed to write generated spec index");
}

/// Structurally scan a top-level JSON object, returning `(key, value_start,
/// value_end)` byte offsets for each entry, without deserializing the
/// values. `value_start..value_end` is a valid standalone JSON value slice.
fn scan_top_level_object(bytes: &[u8]) -> Result<Vec<(String, usize, usize)>, String> {
    let mut i = skip_ws(bytes, 0);
    if bytes.get(i) != Some(&b'{') {
        return Err("expected top-level JSON object".to_string());
    }
    i += 1;
    let mut entries = Vec::new();
    loop {
        i = skip_ws(bytes, i);
        if bytes.get(i) == Some(&b'}') {
            break;
        }
        if bytes.get(i) != Some(&b'"') {
            return Err(format!("expected key string at byte {i}"));
        }
        let (key, key_end) = scan_string(bytes, i)?;
        i = skip_ws(bytes, key_end);
        if bytes.get(i) != Some(&b':') {
            return Err(format!("expected ':' at byte {i}"));
        }
        i += 1;
        i = skip_ws(bytes, i);
        let value_start = i;
        let value_end = skip_value(bytes, i)?;
        entries.push((key, value_start, value_end));
        i = skip_ws(bytes, value_end);
        match bytes.get(i) {
            Some(b',') => {
                i += 1;
            }
            Some(b'}') => {
                break;
            }
            other => return Err(format!("expected ',' or '}}' at byte {i}, found {other:?}")),
        }
    }
    Ok(entries)
}

fn skip_ws(bytes: &[u8], mut i: usize) -> usize {
    while let Some(&b) = bytes.get(i) {
        if b == b' ' || b == b'\t' || b == b'\n' || b == b'\r' {
            i += 1;
        } else {
            break;
        }
    }
    i
}

/// Parse a JSON string starting at `bytes[i]` (which must be `"`), returning
/// the decoded key and the byte offset just past the closing quote. Only
/// used for object keys, which in this catalog are plain ASCII tool names,
/// so this does not need full unicode-escape decoding beyond what's needed
/// to correctly find the end of the string.
fn scan_string(bytes: &[u8], start: usize) -> Result<(String, usize), String> {
    let mut i = start + 1;
    let mut s = String::new();
    loop {
        match bytes.get(i) {
            None => return Err("unterminated string".to_string()),
            Some(b'"') => {
                i += 1;
                break;
            }
            Some(b'\\') => {
                let esc = bytes.get(i + 1).ok_or("dangling escape")?;
                match esc {
                    b'"' => s.push('"'),
                    b'\\' => s.push('\\'),
                    b'/' => s.push('/'),
                    b'n' => s.push('\n'),
                    b't' => s.push('\t'),
                    b'r' => s.push('\r'),
                    b'b' => s.push('\u{8}'),
                    b'f' => s.push('\u{c}'),
                    b'u' => {
                        let hex = bytes.get(i + 2..i + 6).ok_or("truncated unicode escape")?;
                        let hex_str = std::str::from_utf8(hex).map_err(|e| e.to_string())?;
                        let code = u32::from_str_radix(hex_str, 16).map_err(|e| e.to_string())?;
                        if let Some(c) = char::from_u32(code) {
                            s.push(c);
                        }
                        i += 4;
                    }
                    other => return Err(format!("unknown escape \\{}", *other as char)),
                }
                i += 2;
            }
            Some(&b) => {
                // Collect raw UTF-8 bytes until the next quote/backslash.
                let start_run = i;
                while let Some(&b2) = bytes.get(i) {
                    if b2 == b'"' || b2 == b'\\' {
                        break;
                    }
                    i += 1;
                }
                if i == start_run {
                    // Shouldn't happen given the match arms above, but keep
                    // the loop provably terminating.
                    s.push(b as char);
                    i += 1;
                } else {
                    s.push_str(
                        std::str::from_utf8(&bytes[start_run..i]).map_err(|e| e.to_string())?,
                    );
                }
            }
        }
    }
    Ok((s, i))
}

/// Skip over one JSON value starting at `bytes[i]`, returning the offset
/// just past it. Handles objects, arrays, strings, numbers, and literals,
/// recursively, tracking string/escape state so braces inside strings don't
/// confuse nesting depth.
fn skip_value(bytes: &[u8], i: usize) -> Result<usize, String> {
    match bytes.get(i) {
        Some(b'"') => {
            let (_, end) = scan_string(bytes, i)?;
            Ok(end)
        }
        Some(b'{') => skip_bracketed(bytes, i, b'{', b'}'),
        Some(b'[') => skip_bracketed(bytes, i, b'[', b']'),
        Some(b't') => Ok(i + 4), // true
        Some(b'f') => Ok(i + 5), // false
        Some(b'n') => Ok(i + 4), // null
        Some(&b) if b == b'-' || b.is_ascii_digit() => {
            let mut j = i;
            while let Some(&c) = bytes.get(j) {
                if c.is_ascii_digit() || matches!(c, b'-' | b'+' | b'.' | b'e' | b'E') {
                    j += 1;
                } else {
                    break;
                }
            }
            Ok(j)
        }
        other => Err(format!("unexpected byte {other:?} at offset {i}")),
    }
}

fn skip_bracketed(bytes: &[u8], start: usize, open: u8, close: u8) -> Result<usize, String> {
    let mut i = start + 1;
    let mut depth = 1usize;
    loop {
        match bytes.get(i) {
            None => return Err("unterminated object/array".to_string()),
            Some(b'"') => {
                let (_, end) = scan_string(bytes, i)?;
                i = end;
            }
            Some(&b) if b == open => {
                depth += 1;
                i += 1;
            }
            Some(&b) if b == close => {
                depth -= 1;
                i += 1;
                if depth == 0 {
                    return Ok(i);
                }
            }
            Some(_) => {
                i += 1;
            }
        }
    }
}
