#!/usr/bin/env bash
# Framework-support matrix (spec §13.1a, batch 6 part 6).
#
# Runs `mandible --doctor` against one representative tool per supported
# framework and checks that Tier A′ identifies the framework we expect and
# that Tier B extracts a non-trivial tree. Emits a markdown table to
# $GITHUB_STEP_SUMMARY (or stdout when run locally) and exits non-zero if
# any expected framework was not detected.
#
# The point of this script existing as a file rather than inline YAML: it
# runs identically on a laptop (`scripts/framework_matrix.sh`) and in CI,
# so "the workflow is broken" is debuggable without pushing commits.
#
# Each CASES entry is `expected_framework|tool|note`. `expected_framework`
# matches against the *name* `Framework::name()` prints, and a leading `?`
# means "informational only, do not fail the build" — used for frameworks
# whose representative tool isn't reliably installable in the runner
# budget.
set -uo pipefail

MANDIBLE="${MANDIBLE:-mandible}"
SUMMARY="${GITHUB_STEP_SUMMARY:-/dev/stdout}"

# Note on the clap representative: it is deliberately NOT ripgrep, the
# obvious choice. ripgrep dropped clap in v14 for a hand-rolled parser, so
# `rg` fingerprints as unidentified — correctly. It is also not `cargo`,
# which on most systems is a rustup shim: spec §6 redirects HOME to a
# scratch directory (so a probe can never write into the real one, [M-11]),
# and rustup resolves its toolchain through HOME, so the shim prints
# "rustup could not choose a version of cargo to run" instead of help.
# `fd` (Debian/Ubuntu binary name `fdfind`) is a plain clap v4 binary with
# neither problem.
CASES=(
  "GNU argp/getopt_long|tar|coreutils/tar, the largest measured fingerprint (15.5%, [M-12])"
  "clap (v3/v4)|fdfind|fd-find, apt"
  "cobra|gh|preinstalled on GitHub-hosted runners"
  "cobra|docker|preinstalled on GitHub-hosted runners"
  "argparse|mandible-argparse-fixture|this repo's own fixture, generated by the workflow"
  "click|black|pip"
  # busybox is INFORMATIONAL, not because it is unimportant but because the
  # grammar for it is honestly incomplete: `busybox --help` lists its
  # applets tab-indented and comma-separated ("[, [[, acpid, add-shell,
  # ...") rather than in the aligned columns the bare-name grid parser
  # requires, so it fingerprints correctly and then yields an empty tree.
  # Marked `?` so the table keeps reporting it — an unmeasured or broken
  # framework should look that way, not disappear — without a known,
  # documented gap turning the badge red on every unrelated commit.
  "?busybox|busybox|apt — applet-list grammar not implemented yet"
  "commander|mandible-commander-fixture|generated by this workflow, npm"
  "go flag|mandible-goflag-fixture|generated by this workflow, go build"
  "?picocli|mandible-picocli-fixture|skipped unless a jar is available"
)

failures=0
rows=""

for case in "${CASES[@]}"; do
  IFS='|' read -r expected tool note <<<"$case"

  optional=0
  if [[ "$expected" == \?* ]]; then
    optional=1
    expected="${expected#?}"
  fi

  if ! command -v "$tool" >/dev/null 2>&1; then
    rows+="| ${expected} | \`${tool}\` | _not installed_ | — | — | — | $([[ $optional == 1 ]] && echo 'skipped' || echo '**FAIL**') |"$'\n'
    [[ $optional == 1 ]] || failures=$((failures + 1))
    continue
  fi

  out="$("$MANDIBLE" --doctor "$tool" 2>&1)"
  detected="$(sed -n 's/^framework:[[:space:]]*//p' <<<"$out" | head -1)"
  nodes="$(sed -n 's/^nodes:[[:space:]]*//p' <<<"$out" | head -1)"
  flags_line="$(sed -n 's/^flags:[[:space:]]*//p' <<<"$out" | head -1)"
  flags="${flags_line%% *}"
  pct="$(sed -n 's/.*(\([0-9.]*\)% described).*/\1%/p' <<<"$flags_line")"

  # `detected` carries the detection method too ("cobra (from artifact)");
  # the expectation is on the framework, not on which step identified it,
  # since artifact-vs-signature can legitimately flip with a tool rebuild.
  if [[ "$detected" == "$expected"* ]]; then
    # Non-trivial tree: at least one flag or one subcommand. A tool that
    # identifies correctly but extracts nothing is a Tier B failure, and
    # this matrix is the only place that distinction gets checked.
    if [[ "${nodes:-0}" -gt 1 || "${flags:-0}" -gt 0 ]]; then
      verdict="ok"
    else
      verdict="**FAIL** (empty tree)"
      [[ $optional == 1 ]] || failures=$((failures + 1))
    fi
  else
    verdict="**FAIL** (expected ${expected})"
    [[ $optional == 1 ]] || failures=$((failures + 1))
  fi

  rows+="| ${expected} | \`${tool}\` | ${detected:-—} | ${nodes:-—} | ${flags:-—} | ${pct:-—} | ${verdict} |"$'\n'
done

# Written to stdout *and* the step summary. Summary-only output meant a
# failing run showed an exit code and nothing else in the logs, which is
# precisely when you need to see the table.
{
  echo "## Framework support matrix"
  echo
  echo "One representative tool per supported framework (spec §7 Tier A′/Tier B)."
  echo "Knowledge in mandible is keyed by *framework*, never by tool — this table is"
  echo "the check that the bounded, ~18-entry framework set actually covers real CLIs."
  echo
  echo "| framework | tool | detected | nodes | flags | %described | result |"
  echo "|---|---|---|---|---|---|---|"
  printf '%s' "$rows"
  echo
  if [[ $failures -eq 0 ]]; then
    echo "All required frameworks detected."
  else
    echo "**${failures} framework check(s) failed.**"
  fi
} | tee -a "$SUMMARY"

exit $((failures > 0 ? 1 : 0))
