//! Computes `SOURCE_FINGERPRINT`: a hash of every `.rs` file under
//! `mantui-core/src` and `mantui-extract/src` — the crates that actually
//! decide what a cached extraction *means* (the IR, sanitization, merge
//! logic, and every extraction tier).
//!
//! This exists because the cache key previously depended only on a
//! hand-maintained `SCHEMA_VERSION` and `CARGO_PKG_VERSION`, neither of
//! which changes when extraction/parsing/sanitization logic changes. That
//! shipped as a real bug: a user upgrading mantui to get a parser fix kept
//! serving their stale, wrong cached tree indefinitely, because nothing
//! about the on-disk key changed. `SCHEMA_VERSION` is right for on-disk
//! *format* changes; it was never the right tool for "did the code that
//! produces this data change," and a correctness invariant that depends on
//! a human remembering to bump a version number by hand was always going
//! to fail eventually — it already had.
//!
//! `cargo` reruns this build script whenever a file under either watched
//! directory changes (`cargo:rerun-if-changed` on a directory is
//! recursive), so the fingerprint — and therefore the cache key — updates
//! automatically on every extraction-logic change, with no step to
//! remember.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let watched_dirs = [
        manifest_dir.join("../mantui-core/src"),
        manifest_dir.join("../mantui-extract/src"),
    ];

    let mut files: Vec<PathBuf> = Vec::new();
    for dir in &watched_dirs {
        println!("cargo:rerun-if-changed={}", dir.display());
        collect_rs_files(dir, &mut files);
    }
    // Deterministic across platforms/runs regardless of directory
    // iteration order.
    files.sort();

    let mut hasher = Fnv1a64::new();
    for path in &files {
        let rel = path
            .strip_prefix(&manifest_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/"); // normalize Windows separators
        hasher.update(rel.as_bytes());
        hasher.update(&[0]); // separator, so "ab"+"c" != "a"+"bc" in path/content framing
        let contents =
            fs::read(path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        hasher.update(&contents);
        hasher.update(&[0]);
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = Path::new(&out_dir).join("source_fingerprint.rs");
    fs::write(
        &dest,
        format!(
            "// @generated by mantui-cache/build.rs. Do not edit.\n\
             pub(crate) const SOURCE_FINGERPRINT: u64 = {:#018x};\n\
             /// Only read in tests today (a sanity check that the build\n\
             /// script actually hashed something); kept `pub(crate)` and\n\
             /// allowed dead-code rather than `#[cfg(test)]`-gated, since\n\
             /// a real diagnostic (e.g. `--doctor`) may want it later.\n\
             #[allow(dead_code)]\n\
             pub(crate) const SOURCE_FINGERPRINT_FILE_COUNT: usize = {};\n",
            hasher.finish(),
            files.len(),
        ),
    )
    .expect("failed to write generated source fingerprint");
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        // Missing directory (e.g. a packaging context that vendors only
        // this crate) degrades to an empty contribution rather than
        // failing the build.
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

/// FNV-1a 64-bit. Not for security — just a small, dependency-free,
/// deterministic hash (unlike `std::collections::hash_map::DefaultHasher`,
/// which is not guaranteed stable across compilations) suitable for a
/// build-time content fingerprint.
struct Fnv1a64 {
    state: u64,
}

impl Fnv1a64 {
    const OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
    const PRIME: u64 = 0x0000_0100_0000_01b3;

    fn new() -> Self {
        Fnv1a64 {
            state: Self::OFFSET_BASIS,
        }
    }

    fn update(&mut self, bytes: &[u8]) {
        for &b in bytes {
            self.state ^= b as u64;
            self.state = self.state.wrapping_mul(Self::PRIME);
        }
    }

    fn finish(&self) -> u64 {
        self.state
    }
}
